version: "3"

services:
  nuxt:
    image: username/nuxtjs-app
    restart: always
    container_name: nuxt
    ports:
      - "5000:3000"
    environment:
      VIRTUAL_HOST: domain.name
#      VIRTUAL_PORT: 1880
      LETSENCRYPT_HOST: domain.name
      LETSENCRYPT_EMAIL: email
networks:
 default:
  external:
    name: nginxproxy_default